export declare const isUndefined: (value: any) => Boolean;
export declare const isNumber: (value: any) => Boolean;
export declare const isString: (value: any) => Boolean;
export declare const isBoolean: (value: any) => Boolean;
export declare const isNull: (value: any) => Boolean;
export declare const isFunction: (value: any) => Boolean;
export declare const isObject: (value: any) => Boolean;
export declare const isNaN: (value: any) => Boolean;
export declare const isArrayObject: (value: object) => Boolean;
export declare const isNumberObject: (value: object) => Boolean;
export declare const isStringObject: (value: object) => Boolean;
export declare const isBooleanObject: (value: object) => Boolean;
export declare const isSymbol: (value: any) => Boolean;
export declare const isBigint: (value: any) => Boolean;
declare const _default: {
    isUndefined: (value: any) => Boolean;
    isNumber: (value: any) => Boolean;
    isString: (value: any) => Boolean;
    isBoolean: (value: any) => Boolean;
    isNull: (value: any) => Boolean;
    isFunction: (value: any) => Boolean;
    isObject: (value: any) => Boolean;
    isNaN: (value: any) => Boolean;
    isArrayObject: (value: object) => Boolean;
    isNumberObject: (value: object) => Boolean;
    isStringObject: (value: object) => Boolean;
    isBooleanObject: (value: object) => Boolean;
    isSymbol: (value: any) => Boolean;
    isBigint: (value: any) => Boolean;
};
export default _default;
